vars:
  - config.json

stages:
  ingest:
    cmd: python src/ingestion.py ${input_folder_path} ${output_folder_path}
    deps: 
    - src/ingestion.py
    - ${input_folder_path}
    outs:
    - ${output_folder_path}/finaldata.csv
    - ${output_folder_path}/ingesteddata.txt

  train:
    cmd: python src/training.py ${output_folder_path} ${output_model_path} 
    deps: 
    - src/ingestion.py
    - ${input_folder_path}
    params:
    - train
    outs:
    - ${output_model_path}/trainedmodel.pkl

  scoring:
    cmd: python src/scoring.py ${output_model_path} ${test_data_path} 
    deps: 
    - src/scoring.py
    - ${test_data_path}/testdata.csv
    params:
    - train
    outs:
    - ${output_model_path}/latestscore.txt