vars:
  - config.json

stages:
  ingest:
    cmd: python src/ingestion.py
    deps: 
    - src/ingestion.py
    - ${input_folder_path}
    outs:
    - ${output_folder_path}/finaldata.csv
    - ${output_folder_path}/ingesteddata.txt

  train:
    cmd: python src/training.py
    deps: 
    - src/ingestion.py
    - ${output_folder_path}/finaldata.csv
    params:
    - train
    outs:
    - ${output_model_path}/trainedmodel.pkl

  scoring:
    cmd: python src/scoring.py
    deps: 
    - src/scoring.py
    - ${test_data_path}/testdata.csv
    - ${output_model_path}/trainedmodel.pkl
    params:
    - train
    outs:
    - ${output_model_path}/latestscore.txt

  deploy:
    cmd: python src/deployment.py 
    deps: 
    - src/deployment.py
    - ${output_folder_path}/ingesteddata.txt
    - ${output_model_path}/latestscore.txt
    - ${output_model_path}/trainedmodel.pkl
    outs:
    - ${prod_deployment_path}/ingesteddata.txt
    - ${prod_deployment_path}/latestscore.txt
    - ${prod_deployment_path}/trainedmodel.pkl

    